// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2C0WBfn-paz7obvHuKu7hGekI16hJkU',
    appId: '1:988109124922:web:bfaf0689675290f5534c03',
    messagingSenderId: '988109124922',
    projectId: 'smart-home-9e959',
    authDomain: 'smart-home-9e959.firebaseapp.com',
    databaseURL: 'https://smart-home-9e959-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-9e959.appspot.com',
    measurementId: 'G-W30ZKPR4XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp2l4wDVlltTXtEIaTBobUnyRCeW-IeCw',
    appId: '1:988109124922:android:10ec343c942ba0c5534c03',
    messagingSenderId: '988109124922',
    projectId: 'smart-home-9e959',
    databaseURL: 'https://smart-home-9e959-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-9e959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpuMxxo0vNOcg9y1qOQOlursdH0yCMF1g',
    appId: '1:988109124922:ios:3a87ab7a616ae8e0534c03',
    messagingSenderId: '988109124922',
    projectId: 'smart-home-9e959',
    databaseURL: 'https://smart-home-9e959-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-9e959.appspot.com',
    iosClientId: '988109124922-4jv63j72s8jgln49qq0a2qmro6629ao8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiDddTest1',
  );
}
